# You'll need to download and source your credentials before this will work:
#  https://research.csc.fi/pouta-credentials
#

- name: Create virtual machine on cPouta
  hosts: localhost # The OpenStack Shade modules run by Shade on your local machine.
  #connection: local
  vars: 
  roles:
    - role: kielipankki.common.create_instances
      tags: create_instances

- name: Install Portal
  hosts: webanno-pre-prod
  remote_user: cloud-user
  become: yes  # sudo to root

  roles:
    - role: kielipankki.common.backup
      tags: backup
    - role: kielipankki.common.postfix
      tags: postfix
    - role: zaxos.tomcat-ansible-role
      tags: tomcat-install
    - role: tomcat
      tags: tomcat-configure
    - role: mariadb
      tags: mariadb
    - role: webanno
      tags: webanno
    - role: firewall
      tags: firewall


